-- SQL to create the vehicle_records table in Supabase
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS vehicle_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plate_number TEXT NOT NULL,
  vehicle_type TEXT,
  plate_color TEXT,
  confidence FLOAT,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  image_url TEXT,
  make TEXT,
  model TEXT,
  location TEXT,
  status TEXT
);

-- Create an index on plate_number for fast searches
CREATE INDEX IF NOT EXISTS idx_vehicle_records_plate_number ON vehicle_records (plate_number);

-- Optional: Enable Row Level Security (RLS)
-- ALTER TABLE vehicle_records ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow public read" ON vehicle_records FOR SELECT USING (true);
-- CREATE POLICY "Allow public insert" ON vehicle_records FOR INSERT WITH CHECK (true);
